<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2023/08/15 10:33:50
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfpropelroute' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfwebdebugpanelpropel' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfpropeldatabase' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfvalidatorpropelunique' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfvalidatorpropelchoice' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfformpropel' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfformfilterpropel' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfpropelformgenerator' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelformfiltergenerator' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelgenerator' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropelbehaviorbase' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviorsymfonybehaviors' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviori18ntranslation' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviori18n' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviortimestampable' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropelpager' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropel' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfmixer' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropelmanytomany' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropeldatabaseschema' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropeldata' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropelbehavior' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'swift_propelspool' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropellogger' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelbuildmodeltask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildsqltask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbasetask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildtask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelbuildfilterstask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelgenerateadmintask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropeldatadumptask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropelgeneratemoduletask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfphing' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfpropeldataloadtask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelbuildschematask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelgraphviztask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelschematoymltask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sfpropelinsertsqltask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfphinglistener' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelconfiguredatabasetask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropelbuildallloadtask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildformstask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelschematoxmltask' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfwidgetformpropelchoice' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',
  'sftesterpropel' => '/opt/symfony1-1.4.20/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',

  // project
  'baseform' => '/app/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => '/app/apps/frontend/lib/myUser.class.php',

  // modules
);
